@echo off
REM Remove every build cache. Everything in them is regenerated by a build.
setlocal

for /d /r %%d in (.cache) do (
    if exist "%%d" (
        echo removing %%d
        rmdir /s /q "%%d"
    )
)

echo === all caches removed ===
exit /b 0
